# Generated by Django 2.2 on 2020-05-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookieagr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
