# Generated by Django 2.2 on 2020-05-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='gallery')),
                ('name', models.CharField(max_length=150)),
                ('pkg', models.TextField()),
                ('pname', models.TextField()),
            ],
        ),
    ]
